name: Calling Workflow

on:
    push:
        branches: [main]


jobs:
    Calling_Workflow:
       uses: ./.github/workflows/reusable-build.yml
       with:
         app_name: "First_App"
         environment: "production"
       secrets:
         docker_token: ${{ secrets.DOCKERHUB_TOKEN }}