name: CICD - Taking Inputs During manual trigger

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose one of them
        type: choice
        default: dev
        required: true
        options:
          - dev
          - prod
          - staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        run: echo "This is my Code"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Building the app
        run: echo "Build Started"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Testing the app
        run: echo "App testing has been initiated"
  deploy:
    if: inputs.environment == 'dev'
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: App Deployment has been started
        run: echo "App has been deployed "
        
