# Packages issues or Vulnerabilities Scan
# Tools Name : pip-audit

name: Dependencies Scan 

on:
    workflow_call: 

jobs:
    Dependency_Scan:
        runs-on: ubuntu-latest
        steps:            
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python 3.14
              uses: actions/setup-python@v5
              with:
                python-version: "3.14"

            - name: Pip Dependency Audit
              run: pip install pip-audit

            - name: Audit Dependencies
              run: pip-audit -r requirements.txt

          
