name: DevSecOps End to End Pipeline

on:
  workflow_dispatch:      
#   push:
#     branches: [main]


jobs:

    # CI (Continuous Integration with Security Scanning)

    code_quality:
        uses: ./.github/workflows/code-quality.yml
    
    secrets_scan:
        uses: ./.github/workflows/secrets-scan.yml
        
    
    dependencies_check:
        uses: ./.github/workflows/dependencies-scan.yml
        

    docker_lint:
        uses: ./.github/workflows/docker-lint.yml
        
    # Build Once the security scans are complete

    build:
        needs: [code_quality , secrets_scan , dependencies_check , docker_lint]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit
        
        
    image_scan:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    deploy:
        needs: [image_scan]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit