name: Docker Build and Push

on:
    push:
        branches: [main]


jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4        


            - name: Build Docker Image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: false
                tags: ${{ vars.DOCKERHUB_USERNAME }}/python-app:latest
                                  

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            
            - name: Push Docker Image
              if: github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ vars.DOCKERHUB_USERNAME }}/python-app:latest
                    ${{ vars.DOCKERHUB_USERNAME }}/python-app:${{ github.sha }}