name: GitHub Secrets

on:
    # push:
      workflow_dispatch: 


jobs:
    Check_Secret:
        runs-on: ubuntu-latest
        env: 
            MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        steps:
            - name: Check for Secret
              if: ${{ env.MY_SECRET != '' }}
              run: echo "Secret has been set"

            - name: Printing Secret
              run: |
                echo ${{ env.MY_SECRET }}  
                echo ${{ secrets.MY_SECRET_MESSAGE }}
        