name: Python Lint

on:
    push: 
      branches: [main]

jobs:
    Python_Installation:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix: 
            os: [ubuntu-latest , windows-latest]
            python-version: ["3.10","3.11","3.12"]
            exclude:
              - python-version: "3.10"
                os: windows-latest
        steps:
            - name: Installing Python (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: |
                sudo add-apt-repository ppa:deadsnakes/ppa -y
                sudo apt-get update
                sudo apt-get install python${{ matrix.python-version }} -y

            - name: Installing Python (Windows)
              if: matrix.os == 'windows-latest'
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Verify Installation
              run: python${{ matrix.python-version }} -V
