name: Passing Output from Job to Job 

on:
  workflow_dispatch:


jobs:
  Job1:
    runs-on: ubuntu-latest
    outputs:
      job1_output: ${{ steps.job_id.outputs }}
    steps:      
      - name: OutPut
        id: job_id
        run: echo "This sentence is printing from job1"

  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - name: Taking Output from Job1
        run: echo "OutPut of Job1 is - ${{ needs.Job1.outputs.job1_output }}"