name: Cron Trigger

on:
    # schedule:
    #     - cron: '30 2 * * 1'
    #     - cron: '0 */6 * * *'
    #     - cron: '0 00 1 * *'
    workflow_dispatch: 


jobs:
    Trigger_Time:
        runs-on: ubuntu-latest
        steps:
            - name: Schedule triggered time
              run: echo "Trigger time is ${{ github.event.schedule }}"

            - name: Health Check
              run: |
                URL="https://api.github.com/this-does-not-exist"
                
                STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
                echo "Response code: $STATUS_CODE"
                
                if [[ "$STATUS_CODE" -ge 200 && "$STATUS_CODE" -lt 300 ]]; then
                    echo "Service is healthy."
                else
                    echo "Service returned unhealthy status: $STATUS_CODE"
                    exit 1
                fi