name: Smart Pipeline

on:
    # push:
      workflow_dispatch: 


jobs:
    lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: Linting Job
              run: echo "Lint start"

    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Testing Job
              run: echo "Test Job"

    summary-job:         
        runs-on: ubuntu-latest
        needs: [ lint-job , test-job]
        steps:
            - name: Summary Report
              run: |
                # echo "Branch name ${{ github.ref_name }}"             
                if [ "${{ github.ref_name }}" == "main" ]; then
                  echo "This is a push to the main branch"
                else
                  echo "This is a push to a feature branch: ${{ github.ref_name }}"
                fi
                echo "Event name ${{ github.event_name }}"
                echo "Commit Message ${{ github.event.head_commit.message }}"