name: Schedule Trigger

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Scheduled Trigger
        run: echo "This workflow at runs every 5 minutes"
