name: Hello Workflow

on:
  push:

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Print Message 
        run: echo "Hello from GitHub Actions"

      - name: Get current date
        run: echo "$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Print branch name
        run: echo "The branch is $GITHUB_REF_NAME"
  
      - name: List Files in repo
        run: git ls-files

      - name: Print OS via Context
        run: echo "The runner OS context is ${{ runner.os }}"

      - name: On purpose error 
        run: dcoker --version