name: Calling Composite Action

on:
    push:
        branches: [main]


jobs: 
    greeting:
        runs-on: ubuntu-latest        
        steps:
            - name: Run Greet Action
              id: greet-action
              uses: ./.github/actions/setup-and-greet
              with:
                name: "Prem"
                language: "Hindi"

            - name: Confirm Greeted
              run: echo "Greeted status ${{ steps.greet-action.outputs.greeted }}"